/**
 * Eigene Wortliste für „Codenamen“: bekannte Begriffe, gern mit mehreren Bedeutungen (Schloss, Bank, Birne …),
 * damit sich gute Hinweise finden lassen. Keine Kopie der Originalkarten.
 */
export const WORDS: readonly string[] = [
  "Abenteuer", "Adler", "Affe", "Akku", "Alarm", "Alpen", "Ameise", "Amerika", "Ananas", "Angel",
  "Anker", "Anzug", "Apfel", "Apotheke", "Arena", "Arm", "Arzt", "Ast", "Atlas", "Auge",
  "Auto", "Axt", "Baby", "Bach", "Bad", "Bahn", "Ball", "Band", "Bank", "Bär",
  "Bart", "Batterie", "Bauer", "Baum", "Becher", "Beere", "Berg", "Besen", "Bett", "Biene",
  "Bier", "Bild", "Birne", "Blatt", "Blitz", "Blume", "Bock", "Boden", "Bogen", "Bohne",
  "Boot", "Börse", "Botschaft", "Brand", "Brief", "Brille", "Brot", "Brücke", "Brunnen", "Buch",
  "Burg", "Bus", "Butter", "Chef", "Chip", "Clown", "Code", "Dach", "Dame", "Daumen",
  "Decke", "Diamant", "Dieb", "Drache", "Drehbuch", "Dusche", "Ecke", "Ei", "Eimer", "Eis",
  "Elefant", "Engel", "Ente", "Erde", "Essig", "Eule", "Fabrik", "Faden", "Fahne", "Fall",
  "Fallschirm", "Farbe", "Feder", "Fee", "Fenster", "Ferien", "Fest", "Feuer", "Figur", "Film",
  "Finger", "Fisch", "Flasche", "Fledermaus", "Fleisch", "Fliege", "Flöte", "Flügel", "Flugzeug", "Fluss",
  "Form", "Frosch", "Fuchs", "Funke", "Fuß", "Gabel", "Gans", "Garten", "Gas", "Geist",
  "Geld", "Geschenk", "Gesicht", "Gewitter", "Gift", "Gipfel", "Gitarre", "Glas", "Glocke", "Glück",
  "Gold", "Golf", "Gras", "Grenze", "Gummi", "Gurke", "Gürtel", "Hafen", "Hahn", "Hai",
  "Hals", "Hammer", "Hand", "Handy", "Harfe", "Hase", "Haus", "Haut", "Hecht", "Heft",
  "Held", "Helm", "Hemd", "Herz", "Heu", "Hexe", "Himmel", "Hitze", "Hof", "Höhle",
  "Holz", "Honig", "Horn", "Hose", "Hotel", "Hund", "Hut", "Hütte", "Igel", "Insel",
  "Jacke", "Jäger", "Joker", "Kabel", "Käfer", "Kaffee", "Käfig", "Kaiser", "Kaktus", "Kamel",
  "Kamera", "Kamm", "Kanal", "Kanone", "Kapitän", "Karte", "Käse", "Kasse", "Katze", "Kegel",
  "Keks", "Keller", "Kerze", "Kette", "Kiefer", "Kino", "Kirche", "Kirsche", "Kiste", "Kiwi",
  "Klavier", "Klee", "Knie", "Knopf", "Knoten", "Koch", "Koffer", "Komet", "König", "Kopf",
  "Korb", "Korken", "Krabbe", "Kraft", "Kran", "Krebs", "Kreide", "Kreis", "Kreuz", "Krieg",
  "Krone", "Kröte", "Kuchen", "Kugel", "Kuh", "Küste", "Labor", "Lampe", "Land", "Laser",
  "Laub", "Lehrer", "Leiter", "Licht", "Linse", "Löffel", "Löwe", "Luft", "Magnet", "Mais",
  "Mantel", "Mars", "Maske", "Mast", "Matte", "Maus", "Meer", "Messer", "Mikroskop", "Milch",
  "Mine", "Mond", "Motor", "Mücke", "Mühle", "Mumie", "Mund", "Museum", "Muschel", "Musik",
  "Mutter", "Nacht", "Nadel", "Nagel", "Nase", "Nebel", "Nest", "Netz", "Note", "Nuss",
  "Oase", "Ofen", "Ohr", "Oktopus", "Oper", "Orange", "Orgel", "Paket", "Palast", "Palme",
  "Panzer", "Papier", "Park", "Pass", "Pater", "Pause", "Pech", "Pfanne", "Pfeffer", "Pfeife",
  "Pfeil", "Pferd", "Pflaster", "Pilot", "Pilz", "Pinguin", "Pinsel", "Pirat", "Pizza", "Planet",
  "Platte", "Polizei", "Post", "Prinz", "Punkt", "Puppe", "Pyramide", "Quelle", "Rabe", "Rad",
  "Rakete", "Rasen", "Ratte", "Raum", "Regen", "Reifen", "Riese", "Ring", "Ritter", "Rock",
  "Roboter", "Rolle", "Rose", "Rücken", "Ruder", "Sack", "Saft", "Salz", "Sand", "Satellit",
  "Schach", "Schaf", "Schal", "Schatten", "Schatz", "Schaum", "Schere", "Schiff", "Schild", "Schirm",
  "Schlange", "Schlüssel", "Schloss", "Schnee", "Schnecke", "Schokolade", "Schraube", "Schuh", "Schule", "Schwamm",
  "Schwan", "Schwein", "See", "Segel", "Seife", "Seil", "Sekt", "Sessel", "Sirene", "Ski",
  "Socke", "Sonne", "Spiegel", "Spinne", "Spion", "Spritze", "Stab", "Stadion", "Stahl", "Stamm",
  "Star", "Staub", "Stein", "Stern", "Stiefel", "Stift", "Stock", "Strand", "Straße", "Strauß",
  "Strom", "Stuhl", "Sturm", "Suppe", "Tafel", "Tank", "Tanne", "Tasche", "Taube", "Tee",
  "Teich", "Teller", "Tempel", "Theater", "Tier", "Tiger", "Tinte", "Tisch", "Tod", "Tomate",
  "Topf", "Tor", "Torte", "Traktor", "Traum", "Treppe", "Trommel", "Tuch", "Tunnel", "Tür",
  "Turm", "Uhr", "Ufer", "Ufo", "Vampir", "Vase", "Vogel", "Vulkan", "Waage", "Wal",
  "Wald", "Wand", "Wanze", "Wasser", "Watte", "Welle", "Welt", "Wespe", "Wiege", "Wiese",
  "Wind", "Winter", "Wolf", "Wolke", "Wurm", "Wurst", "Wurzel", "Wüste", "Zahl", "Zahn",
  "Zange", "Zaun", "Zebra", "Zeit", "Zelt", "Zettel", "Ziege", "Ziel", "Zirkus", "Zitrone",
  "Zoll", "Zucker", "Zug", "Zunge", "Zwerg", "Zwiebel",
];
